---
- name: Update cache and Install Nginx
  hosts: ubuntu
  remote_user: _client
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted
